id: AF35B6834
title: Prayer to Khandro Tsering Chödrön
type: translation
pechas:
- I64642441
- I366E901E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:44.847136
  last_modified_at: 2023-01-04 12:48:44.847154
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I64642441/77A7: 07C6
  I366E901E/04FF: 07C6
